name: .NET Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            win-nuget
    - name: Publish Windows
      run: | 
        dotnet publish ./KeyVaultExplorer.Desktop/KeyVaultExplorer.Desktop.csproj --configuration Release --runtime win-x64 --output ${{ github.workspace }}\artifacts\win-x64 -f net8.0-windows10.0.19041.0
        $files = Get-ChildItem -Path "$env:GITHUB_WORKSPACE\artifacts\win-x64"  -Exclude @("*.pdb", "*.dsym","Key Vault Explorer") 
        Compress-Archive -Path $files -DestinationPath "$env:GITHUB_WORKSPACE\artifacts\win-x64.zip"
      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: ${{ github.workspace }}\artifacts\win-x64.zip
      
  build_macos_intel:
    name: Build macOS_intel
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            mac-nuget
    - name: publish_macOS_intel
      run: |
           
        ./KeyVaultExplorer/build.ps1 -Runtime osx-x64 -PublishAot          
        Move-Item -Path "Key Vault Explorer.app" -Destination "$env:GITHUB_WORKSPACE\final\Key Vault Explorer.app
       
      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS_x64
        path: ${{ github.workspace }}/final/

  build_macos:
    name: Build macOS_arm
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            mac-nuget
    - name: Publish macOS Arm
      run: | 
                 
        ./KeyVaultExplorer/build.ps1 -Runtime osx-arm64 -PublishAot          
        Move-Item -Path "Key Vault Explorer.app" -Destination "$env:GITHUB_WORKSPACE\final\Key Vault Explorer.app
        Get-ChildItem -Recurse

      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS_arm64
        path: ${{ github.workspace }}/final/Key Vault Explorer.app
        
  release:
    name: Release code
    needs: [ build_macos, build_windows, build_macos_intel]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Download built artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        run: |
          Get-ChildItem -Recurse
          gh release create v0.0.${{github.run_attempt}} --draft
          gh release upload v0.0.${{github.run_attempt}} "$env:GITHUB_WORKSPACE/win/win-x64.zip" "$env:GITHUB_WORKSPACE/macOS_arm64/mac-arm64.zip" "$env:GITHUB_WORKSPACE/macOS_x64/mac-x64.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
      
      

        
